# Generated by Django 5.2.7 on 2025-10-25 21:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Titel')),
                ('description', models.TextField(verbose_name='Beschreibung')),
                ('trade', models.CharField(max_length=100, verbose_name='Gewerbe')),
                ('zip_code', models.CharField(max_length=10, verbose_name='PLZ')),
                ('status', models.CharField(choices=[('OPEN', 'Offen'), ('IN_PROGRESS', 'In Arbeit'), ('COMPLETED', 'Abgeschlossen')], default='OPEN', max_length=20, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(limit_choices_to={'role': 'CUSTOMER'}, on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to=settings.AUTH_USER_MODEL, verbose_name='Kunde')),
            ],
        ),
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('SUBMITTED', 'Eingereicht'), ('ACCEPTED', 'Angenommen'), ('REJECTED', 'Abgelehnt')], default='SUBMITTED', max_length=20, verbose_name='Bewerbungsstatus')),
                ('cover_letter', models.TextField(blank=True, verbose_name='Anschreiben')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('craftsman', models.ForeignKey(limit_choices_to={'role': 'CRAFTSMAN'}, on_delete=django.db.models.deletion.CASCADE, related_name='applications', to=settings.AUTH_USER_MODEL, verbose_name='Handwerker')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='core.job', verbose_name='Auftrag')),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('job', 'craftsman'), name='unique_job_application')],
            },
        ),
    ]
