# Generated by Django 5.2.7 on 2025-10-26 13:54

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_job_jobapplication'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='assigned_craftsman',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'CRAFTSMAN'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs_assigned', to=settings.AUTH_USER_MODEL, verbose_name='Zugewiesener Handwerker'),
        ),
        migrations.AlterField(
            model_name='job',
            name='customer',
            field=models.ForeignKey(limit_choices_to={'role': 'CUSTOMER'}, on_delete=django.db.models.deletion.CASCADE, related_name='jobs_created', to=settings.AUTH_USER_MODEL, verbose_name='Kunde'),
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Bewertung (1-5 Sterne)')),
                ('comment', models.TextField(blank=True, verbose_name='Kommentar')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='core.job', verbose_name='Auftrag')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
